# Generated by Django 3.0.3 on 2020-03-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('editor', 'Editor'), ('reviewer', 'Reviewer')], default='Author', max_length=100),
        ),
    ]
