# Generated by Django 3.0.3 on 2020-03-21 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200317_1854'),
        ('JournalSubmission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('rejected', models.BooleanField(default=False)),
                ('resubmissions_remaining', models.IntegerField(default=3)),
                ('file', models.FileField(upload_to='uploads/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='users.Profile')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JournalSubmission.Journal')),
                ('reviewer1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer_1', to='users.Profile')),
                ('reviewer2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer_2', to='users.Profile')),
                ('reviewer3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer_3', to='users.Profile')),
            ],
        ),
    ]
