# Generated by Django 3.0.3 on 2020-03-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalSubmission', '0002_auto_20200320_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='editor',
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
