# Generated by Django 3.0.3 on 2020-03-28 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200317_1854'),
        ('JournalSubmission', '0003_auto_20200321_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='journal',
            name='subject',
            field=models.CharField(choices=[('health & medicine', 'Health & Medicine'), ('humanities', 'Humanities'), ('mathematical sciences', 'Mathematical Science'), ('social sciences', 'Social Sciences'), ('physics', 'Physics'), ('computation', 'Computation')], default='Humanities', max_length=200),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='users.Profile'),
        ),
    ]
