# Generated by Django 3.0.3 on 2020-03-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalSubmission', '0004_auto_20200327_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='inReview',
            field=models.BooleanField(default=True),
        ),
    ]
