# Generated by Django 3.0.3 on 2020-03-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalSubmission', '0006_auto_20200330_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='reviewer1_seen',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='reviewer2_seen',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='reviewer3_seen',
        ),
        migrations.AddField(
            model_name='submission',
            name='feedbackReady',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewer1_FEED',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewer2_FEED',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewer3_FEED',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='inReview',
            field=models.BooleanField(default=False),
        ),
    ]
