# Generated by Django 3.0.3 on 2020-03-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalSubmission', '0007_auto_20200331_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='reviewer1_FEED',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewer2_FEED',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewer3_FEED',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
