# Generated by Django 3.0.3 on 2020-03-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalSubmission', '0008_auto_20200331_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='seen_accept',
            field=models.CharField(default='', max_length=6),
        ),
    ]
